# Generated by Django 5.2.12 on 2026-03-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_query', models.TextField(verbose_name='用户查询')),
                ('parsed_params', models.JSONField(default=dict, verbose_name='解析参数')),
                ('routes_count', models.IntegerField(default=0, verbose_name='路线数量')),
                ('recommended_route', models.CharField(blank=True, max_length=50, verbose_name='推荐路线')),
                ('total_time_s', models.FloatField(default=0.0, verbose_name='总耗时(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '路线历史',
                'verbose_name_plural': '路线历史',
                'db_table': 'route_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, default='default', max_length=100, verbose_name='会话ID')),
                ('session_count', models.IntegerField(default=0, verbose_name='会话次数')),
                ('preference_stats', models.JSONField(default=dict, verbose_name='偏好统计')),
                ('route_feedback', models.JSONField(default=dict, verbose_name='路线反馈')),
                ('query_history', models.JSONField(default=list, verbose_name='查询历史(最近50条)')),
                ('last_activity_type', models.CharField(blank=True, max_length=50, verbose_name='最近活动类型')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户记忆',
                'verbose_name_plural': '用户记忆',
                'db_table': 'user_memory',
            },
        ),
    ]
